### PR TITLE
Versioning

### LINKED ISSUE #17: Versioning of the smart contract?

### PR DESCRIPTION
**Pull request by JonathonDunford**
Closes #17 

VERSIONING!

Migration of funds with one request through the smart contract.
Successor / predecessor contracts.
Version # storage.

Big thanks to TokenStore for providing the idea and a decent bit of the implementation: https://github.com/tokenstore/contract/blob/master/contracts/TokenStore.sol

+Some improved in-code documentation.

### CODE REVIEW

**Comment by mmhh1910** [comment]
PR #26 has the changes from #25 and #27 has all the changes from #25 and #26.

**Comment by JonathonDunford** [comment]
@betterdelta 

That's fine. If we go through the PRs in order, the changes will reflect properly. I just didn't want any conflicts on the final PRs, but wanted to separate the issues.

**Comment by mmhh1910** [comment]
> That's fine. If we go through the PRs in order, the changes will reflect properly. I just didn't want any 
> conflicts on the final PRs, but wanted to separate the issues.

Hmm...  This sounds like you assume your PRs will be merged anyway, so what's the point of doing reviews?

Nevermind, we will be able to work this out.

**Comment by JonathonDunford** [comment]
@betterdelta 

Now it's separate: https://github.com/forkdelta/smart_contract/pull/28

**Pull request closed without merging**
