### PR TITLE
Utility contract

### PR DESCRIPTION
**Pull request by lampshade9909**
This contract is intended to be a utility for ForkDelta clients. It may serve many purposes as time goes on, but for now, it is the blockchain component of a client tool that assists users in withdrawing from EtherDelta and/or helping to move funds to ForkDelta's future contract. 

The goal is for a client/web app to call functions in this contract to get lots of information in one API call. Then to use that data to assist users in withdrawing their funds from the EtherDelta contract. For example, The web application could call the "allBalancesForManyAccounts" function and get all balances of all the user's Ethereum wallets and suggest withdraw transactions that withdraw 100% of his funds from EtherDelta (down to the last satoshi)

### CODE REVIEW

**Comment by freeatnet** [comment]
@lampshade9909 This is good stuff! How would we go about testing it out?

**Comment by lampshade9909** [comment]
@freeatnet, You can test it on a local testnet using Remix:

https://remix.ethereum.org/

**Comment by mmhh1910** [comment]
I think will need decent truffle testbed for contracts development. Something like a docker-compose setup that creates a private ethereum network, creates the ED/FD (and other) contract there, sets up some maker/taker accounts and creates some order buy/sell order entries (on-chain) for a token.

Truffle now even has a decent debugger: http://truffleframework.com/blog/announcing-full-portable-solidity-debugger

**Comment by JonathonDunford** [comment]
@lampshade9909 

Any chance you could move this into a `tools` folder?

**Pull request closed without merging**
