### PR TITLE
Migration tool

### PR DESCRIPTION
**Pull request by JonathonDunford**
Closes: https://github.com/forkdelta/smart_contract/issues/21

This is far from finished, but we needed a place to start and a PR to keep track of the progress.

This current `migrate.js` file has the ability to pull balances for all tokens for a given user.

### CODE REVIEW

**Comment by JonathonDunford** [comment]
It seems like the current `getMarket` call in our API requires `token` _and_ `user` passed in before it transmits orders.

This is a bit cumbersome for every token. Maybe we need another API endpoint for getting orders of a user? Maybe `getOrders` where you can pass in user address and/OR token address. Not to mention, it returns ALL of the ticker information on every call to check orders.

@freeatnet thoughts?

**Comment by lampshade9909** [comment]
The contract is being deployed now, see this transactionId.  I'll edit this post with the contract address when it confirms. 

https://etherscan.io/tx/0xb93b368cb76371a96fa9fc2e75e6ad5ff642b48c59dc79fd09a0525011156c77

This contract that will help with the migration process.  With this, you'll shrink hundreds of API calls to Infura down to 1-10 API calls.  It's the exact ForkDeltaUtility contract I wrote in this pull request: [](https://github.com/forkdelta/smart_contract/pull/1)

The two functions you'll want to use for the migration are:  allBalancesForManyAccounts and allBalances.  allBalancesForManyAccounts is great because users tend to have more than one address, so you can check multiple token balances on multiple addresses in one single call.  Or if the user has only one address, but many tokens, you can just use the allBalances function.  You'll need to pass the contract the EtherDelta contract address, the user's address (or array of addresses), and an array of token addresses.  You have a list of token addresses, so just use that list.

**Comment by mmhh1910** [comment]
Please publish the contract source code:

https://etherscan.io/verifyContract?a=0x2256ef3b2b49cf3c0dd24731bc8feaa022db1d0c

**Comment by JonathonDunford** [comment]
This work has been moved here: https://github.com/forkdelta/forkdelta.github.io/pull/129

**Pull request closed without merging**
